version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_START_RPC: "true"
      CASSANDRA_BROADCAST_ADDRESS: 127.0.0.1
      # CASSANDRA_LISTEN_ADDRESS: "0.0.0.0"
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:
